services:
  shared.eventBus:
    class: ../../../contexts/courses/shared/infrastructure/FakeRabbitMqEventBus
    arguments: ['!tagged eventSubscriber']

  shared.commandBus:
    class: ../../../contexts/courses/shared/infrastructure/InMemoryCommandBus
    arguments: []

  shared.queryBus:
    class: ../../../contexts/courses/shared/infrastructure/InMemoryQueryBus
    arguments: []

  videoReview.reviewVideoSubscriber:
    class: ../../../contexts/courses/video/infrastructure/ReviewVideoSubscriber
    arguments: ['@shared.commandBus']
    tags:
      - { name: 'eventSubscriber' }

  videoReview.deleteVideoReviewSubscriber:
    class: ../../../contexts/courses/video/infrastructure/DeleteVideoReviewSubscriber
    arguments: ['@shared.commandBus']
    tags:
      - { name: 'eventSubscriber' }
